apiVersion: v1
kind: pod
metadata:
  name: debug
spec:
  containers:
  - name: debug
    image: alpine:3.12
    command: ["sleep","3600"]
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - web
        topologyKey: kubernetes.io/hostname