apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-example
            image: alpine:1.17
            args:
            - /bin/sh
            - -c
            - tar czvf backup.tar.gz /var/log/*
          restartPolicy: OnFailure
          nodeSelector:
            roles: master