apiVersion: batch/v1
kind: Job
metadata:
  name: init
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init
        image: alpine:3.12
        command: ["/bin/sh"]
        args: ["-c","mkdir /mnt/$BACKUP_DIR"]
        env:
        - name: BACKUP_DIR
          valueFrom:
            configMapKeyRef:
              name: backup-dir
              key: dir
        volumeMounts:
        - name: data
          mountPath: /mnt
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: nfs-pvc