apiVersion: v1
kind: PersistentVolume
metadata:
  name: web
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteOnce
  volumes:
  - name: web
  nfs:
    server: 192.168.98.1
    path: /home/shares/user4