apiVersion: v1
kind: PersistentVolume
metadata:
  name: web
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  volumes:
  - name: web
  nfs:
    server: 192.168.98.1
    path: /home/shares/user4